## Numpy Part 2

In [115]:
import numpy as np

#### 4. Operation

In [116]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum 및 axis

In [117]:
# 모든 요소들의 합
a.sum()

78

In [118]:
# 열의 합
a.sum(axis=0)

array([15, 18, 21, 24])

In [119]:
# 행의 합
a.sum(axis=1)

array([10, 26, 42])

In [120]:
np.sum(a[1])

26

In [121]:
a.min(axis=0)

array([1, 2, 3, 4])

In [122]:
a.max(axis=1)

array([ 4,  8, 12])

In [123]:
a.mean()

6.5

In [124]:
a.mean(axis=0), a.mean(axis=1)

(array([5., 6., 7., 8.]), array([ 2.5,  6.5, 10.5]))

- sorting

In [125]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [126]:
np.sort(b)      # axis = 1, ascending order

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [127]:
np.sort(b, axis=0)

array([[ 1,  3,  1,  7],
       [ 2,  5,  5,  9],
       [ 4, 12, 11, 14]])

In [128]:
b.sort()

In [129]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [130]:
b.sort(axis=0)
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [131]:
# 내림차순
c = np.array([42,38,12,25])
np.sort(c)[::-1]

array([42, 38, 25, 12])

In [132]:
np.argsort(c)

array([2, 3, 1, 0], dtype=int64)

In [133]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

- Mathematical functions

In [134]:
# sigmoid 함수( 1 / (1 + e^(-x)) )
def sigmoid(x):
    return 1. / (1 + np.exp(-x))

In [135]:
X = np.array([-10, 0, 10])
sigmoid(X)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

- Transpose(전치)

In [136]:
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [137]:
b.T

array([[ 1,  1,  3],
       [ 2,  4,  9],
       [ 5,  5, 11],
       [ 7, 12, 14]])

- concatenate, vstack, hstack

In [138]:
a = np.arange(1,5).reshape(2,2)
b = np.array([[5,6]])
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [139]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [140]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [141]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

#### 5. Array operation

- 사칙연산

In [142]:
a

array([[1, 2],
       [3, 4]])

In [143]:
a + a

array([[2, 4],
       [6, 8]])

In [144]:
a - a

array([[0, 0],
       [0, 0]])

In [145]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [146]:
a / a

array([[1., 1.],
       [1., 1.]])

- Broadcasting

In [147]:
a + 3

array([[4, 5],
       [6, 7]])

- Dot product

In [150]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)

In [151]:
np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

In [152]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [154]:
np.dot(np.array([1,2,3]), np.array([4,5,6]))

32

#### 6. Comparison
- all & any

In [156]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [160]:
np.any(a>5)         # 하나라도 True가 있으면 True

True

In [162]:
np.all(a>5)         # 모두 다 True여야 True

False

- Logical operation

In [176]:
b = np.logical_and(a > 3, a < 7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [177]:
np.logical_or(a > 7, a < 3)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax, argmin

In [178]:
a.argmax(), np.argmax(a)

(9, 9)

In [179]:
a.argmin(), np.argmin(a)

(0, 0)

#### 7. Boolean & Fancy indexing
- boolean indexing

In [180]:
# array a 에서 값이 6 이상인 것만 가져오기 - filtering
a[a >= 6]

array([6, 7, 8, 9])

In [181]:
a[b]

array([4, 5, 6])

- fancy indexing

In [184]:
a = np.array([2,4,6,8])
b = np.array([0,0,1,3,2,1])
a[b]

array([2, 2, 4, 8, 6, 4])

#### 8. 기술 통계

In [187]:
a = np.random.randn(10)
a

array([-0.19215902,  1.32829056, -2.1836731 , -0.33225874, -0.57608493,
       -0.82357561, -1.19328702,  0.97927863, -0.85103045, -1.15395263])

In [188]:
# 평균
np.mean(a), a.mean()

(-0.49984523173418227, -0.49984523173418227)

In [189]:
# 표준편차(standard deviation)
np.std(a), a.std()

(0.9813553442978663, 0.9813553442978663)

In [190]:
# 최소, 최대
a.min(), a.max()

(-2.1836731036806163, 1.3282905639245968)

In [191]:
# 사분위수
np.percentile(a, 25), np.percentile(a, 50), np.percentile(a, 75)

(-1.078222084393819, -0.6998302707718651, -0.22718395269447716)

In [192]:
# 중앙값
np.median(a)

-0.6998302707718651

In [193]:
a = np.random.randint(0,3,100)
a

array([1, 1, 1, 1, 0, 2, 1, 0, 1, 0, 2, 2, 1, 2, 2, 2, 2, 0, 0, 1, 0, 1,
       0, 0, 1, 2, 0, 0, 1, 1, 1, 2, 0, 1, 0, 2, 2, 1, 1, 2, 0, 0, 0, 0,
       2, 2, 2, 2, 2, 0, 2, 1, 2, 2, 1, 0, 1, 0, 2, 1, 1, 0, 1, 2, 0, 2,
       0, 0, 0, 1, 2, 2, 1, 0, 2, 1, 1, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 0,
       1, 0, 1, 0, 2, 2, 0, 0, 0, 1, 2, 1])

In [194]:
# 0, 1, 2의 갯수
np.unique(a, return_counts=True)

(array([0, 1, 2]), array([34, 33, 33], dtype=int64))